/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'shgri808' at '4/10/16 12:04 AM' with Gradle 2.9
 *
 * @author shgri808, @date 4/10/16 12:04 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
